apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deployment
spec:
  replicas: 2
  selector:                # âœ… selector hamesha spec ke andar hota hai
    matchLabels:
      app: {{ .Release.Name }}-nginx-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-deployment
    spec:
      containers:
        - name: {{ .Release.Name }}-nginx-deployment
          image: nginx
          ports:
            - containerPort: 80
