apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-deployment
    spec:
      containers:
        - name: {{ .Release.Name }}-nginx-container
          image: "{{ .Values.image }}"
          ports:
            - containerPort: {{ .Values.containerPort }}